# Conexao com MongoDB Atlas (AWS)
spring.data.mongodb.uri=mongodb+srv://mayze07_db_user:<xdLIw4n5FeUUEVV6>@cluster0.eppj3qy.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=engenharia_dados_nosql

# Logging para debug
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.example.cruded=DEBUG

# Porta diferente para nao gerar conflito
server.port=8081