# Conexao com MongoDB Atlas (AWS)
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=engenharia_dados_nosql

# Logging para debug
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.example.cruded=DEBUG

# Porta diferente para nao gerar conflito
server.port=8081